CREATE TABLE [dbo].[ClassLevels]
(
	[CL_PK] UNIQUEIDENTIFIER NOT NULL PRIMARY KEY DEFAULT NEWID(), 
    [CL_Description] VARCHAR(20) NOT NULL DEFAULT '', 
    [CL_SCL_School] UNIQUEIDENTIFIER NOT NULL,
    CONSTRAINT FK_CLASSLEVELS_SCHOOL FOREIGN KEY ([CL_SCL_School]) REFERENCES [Schools](SCL_PK),
)
