CREATE TABLE [dbo].[Classes]
(
	[CLS_PK] UNIQUEIDENTIFIER NOT NULL PRIMARY KEY DEFAULT NEWID(), 
    [CLS_Name] VARCHAR(30) NOT NULL, 
    [CLS_SCL_School] UNIQUEIDENTIFIER NOT NULL, 
    [CLS_StudentMaxNo] INT NOT NULL DEFAULT 0, 
    [CLS_StudentNo] INT NOT NULL DEFAULT 0,
    [CLS_TER_Teacher1] UNIQUEIDENTIFIER NOT NULL,
    [CLS_TER_Teacher2] UNIQUEIDENTIFIER NULL,
    [CLS_TuitionFee] MONEY NOT NULL DEFAULT 0, 
    [CLS_CL_ClassLevel] UNIQUEIDENTIFIER NOT NULL, 
    [CLS_Description] VARCHAR(150) NULL, 
    [CLS_DaysOn] VARCHAR(7) NOT NULL DEFAULT '-------',   [CLS_StartTime] VARCHAR(5) NOT NULL DEFAULT '00:00', 
    [CLS_EndTime] VARCHAR(5) NOT NULL DEFAULT '00:00',  -- SMTWHFS
    CONSTRAINT FK_CLASSES_TEACHER_1 FOREIGN KEY ([CLS_TER_Teacher1]) REFERENCES [Teachers](TER_PK),
    CONSTRAINT FK_CLASSES_TEACHER_2 FOREIGN KEY ([CLS_TER_Teacher2]) REFERENCES [Teachers](TER_PK),
    CONSTRAINT FK_CLASSES_SCHOOL FOREIGN KEY ([CLS_SCL_School]) REFERENCES [Schools](SCL_PK),
    CONSTRAINT FK_CLASSES_CLASSLEVEL FOREIGN KEY ([CLS_CL_ClassLevel]) REFERENCES [ClassLevels](CL_PK)
)
GO
