CREATE TABLE [dbo].[ClassLevels]
(
	[ClassLevelPK] UNIQUEIDENTIFIER NOT NULL PRIMARY KEY DEFAULT NEWID(), 
    [Description] VARCHAR(20) NOT NULL DEFAULT '', 
    [SchoolPK] UNIQUEIDENTIFIER NOT NULL,
    CONSTRAINT FK_CLASSLEVELS_SCHOOL FOREIGN KEY ([SchoolPK]) REFERENCES [Schools](SchoolPK),
)
