CREATE TABLE [dbo].[Classes]
(
	[ClassPK] UNIQUEIDENTIFIER NOT NULL PRIMARY KEY DEFAULT NEWID(), 
    [Name] VARCHAR(30) NOT NULL, 
    [SchoolPK] UNIQUEIDENTIFIER NOT NULL, 
    [StudentMaxNo] INT NOT NULL DEFAULT 0, 
    [StudentNo] INT NOT NULL DEFAULT 0,
    [Teacher1PK] UNIQUEIDENTIFIER NOT NULL,
    [Teacher2PK] UNIQUEIDENTIFIER NULL,
    [TuitionFee] MONEY NOT NULL DEFAULT 0, 
    [ClassLevelPK] UNIQUEIDENTIFIER NOT NULL, 
    [Description] VARCHAR(150) NULL, 
    [DaysOn] VARCHAR(7) NOT NULL DEFAULT '-------',   -- SMTWHFS
    [StartTime] VARCHAR(5) NOT NULL DEFAULT '00:00', 
    [EndTime] VARCHAR(5) NOT NULL DEFAULT '00:00',  
    CONSTRAINT FK_CLASSES_TEACHER_1 FOREIGN KEY (Teacher1PK) REFERENCES [Teachers](TeacherPK),
    CONSTRAINT FK_CLASSES_TEACHER_2 FOREIGN KEY (Teacher2PK) REFERENCES [Teachers](TeacherPK),
    CONSTRAINT FK_CLASSES_SCHOOL FOREIGN KEY (SchoolPK) REFERENCES [Schools](SchoolPK),
    CONSTRAINT FK_CLASSES_CLASSLEVEL FOREIGN KEY (ClassLevelPK) REFERENCES [ClassLevels](ClassLevelPK)
)
