CREATE TABLE [dbo].[Class]
(
	[CLS_PK] UNIQUEIDENTIFIER NOT NULL PRIMARY KEY DEFAULT NEWID(), 
    [CLS_Name] VARCHAR(30) NOT NULL, 
    [CLS_SCL_School] UNIQUEIDENTIFIER NOT NULL, 
    [CLS_StudentMaxNo] INT NOT NULL DEFAULT 0, 
    [CLS_StudentNo] INT NOT NULL DEFAULT 0,
    [CLS_TER_Teacher] UNIQUEIDENTIFIER NOT NULL,
    [CLS_TuitionFee] MONEY NOT NULL DEFAULT 0, 
    [CLS_Level] VARCHAR(20) NULL, 
    [CLS_Description] VARCHAR(150) NULL, 
    CONSTRAINT FK_CLASS_TEACHER FOREIGN KEY ([CLS_TER_Teacher]) REFERENCES [Teacher](TER_PK),
    CONSTRAINT FK_CLASS_SCHOOL FOREIGN KEY ([CLS_SCL_School]) REFERENCES [School](SCL_PK)
)
GO
