CREATE TABLE [dbo].[ClassLevel]
(
	[CL_PK] UNIQUEIDENTIFIER NOT NULL PRIMARY KEY DEFAULT NEWID(), 
    [CL_Description] VARCHAR(20) NOT NULL DEFAULT '', 
    [CL_SCL_School] UNIQUEIDENTIFIER NOT NULL,
    CONSTRAINT FK_CLASSLEVEL_SCHOOL FOREIGN KEY ([CL_SCL_School]) REFERENCES [School](SCL_PK),
)
