CREATE TABLE [dbo].[Class]
(
	[CLS_PK] UNIQUEIDENTIFIER NOT NULL PRIMARY KEY DEFAULT NEWID(), 
    [CLS_Name] VARCHAR(30) NOT NULL, 
    [CLS_LON] UNIQUEIDENTIFIER NOT NULL, 
    [CLS_Student_MaxNo] INT NOT NULL DEFAULT 0, 
    [CLS_Student_No] INT NOT NULL DEFAULT 0,
    [CLS_TER] UNIQUEIDENTIFIER NOT NULL,
    CONSTRAINT FK_CLASS_TEACHER FOREIGN KEY (CLS_TER) REFERENCES [Teacher](TER_PK),
    CONSTRAINT FK_CLASS_LOCATION FOREIGN KEY (CLS_LON) REFERENCES [Location](LON_PK)
)
GO

CREATE NONCLUSTERED INDEX [FK_NDX_CLASS_TEACHER] ON [Class] ([CLS_TER] ASC)
GO

CREATE NONCLUSTERED INDEX [FK_NDX_CLASS_LOCATION] ON [Class] ([CLS_LON] ASC)
GO