CREATE TABLE [dbo].[Creditors]
(
	[CreditorPK] UNIQUEIDENTIFIER NOT NULL PRIMARY KEY DEFAULT NEWID(), 
    [Name] VARCHAR(50) NOT NULL DEFAULT '', 
	[ContactPK] UNIQUEIDENTIFIER,
    CONSTRAINT FK_CREDITORS_CONTACT FOREIGN KEY (ContactPK) REFERENCES [Contacts](ContactPK),
)
