CREATE TABLE [dbo].[Invoice]
(
	[INE_PK] UNIQUEIDENTIFIER NOT NULL PRIMARY KEY DEFAULT NEWID(), 
    [INE_SCL_School] UNIQUEIDENTIFIER NOT NULL,
    [INE_InvoiceNo] VARCHAR(20) NOT NULL DEFAULT '',
    [INE_Description] NVARCHAR(100) NOT NULL DEFAULT '', 
    [INE_DueDate] DATE NOT NULL, 
    [INE_COT_InvoiceFrom] UNIQUEIDENTIFIER NOT NULL, 
    [INE_COT_InvoiceTo] UNIQUEIDENTIFIER NOT NULL, 
    [INE_COT_InvoiceFor] UNIQUEIDENTIFIER NOT NULL, 
    [INE_IsPaid] BIT NOT NULL DEFAULT 0, 
    [INE_IsDeleted] BIT NOT NULL DEFAULT 0, 
    CONSTRAINT FK_INVOICE_SCHOOL FOREIGN KEY ([INE_SCL_School]) REFERENCES [School](SCL_PK),
    CONSTRAINT FK_INVOICE_INVOICEFROM FOREIGN KEY ([INE_COT_InvoiceFrom]) REFERENCES [Contact](COT_PK),
    CONSTRAINT FK_INVOICE_INVOICETO FOREIGN KEY ([INE_COT_InvoiceTo]) REFERENCES [Contact](COT_PK),
    CONSTRAINT FK_INVOICE_INVOICEFOR FOREIGN KEY ([INE_COT_InvoiceFor]) REFERENCES [Contact](COT_PK),
)
