CREATE TABLE [dbo].[Invoices]
(
	[INE_PK] UNIQUEIDENTIFIER NOT NULL PRIMARY KEY DEFAULT NEWID(), 
    [INE_SCL_School] UNIQUEIDENTIFIER NOT NULL,
    [INE_InvoiceNo] VARCHAR(20) NOT NULL DEFAULT '',
    [INE_Description] NVARCHAR(100) NOT NULL DEFAULT '', 
    [INE_DueDate] DATE NOT NULL, 
    [INE_COT_InvoiceFrom] UNIQUEIDENTIFIER NOT NULL, 
    [INE_COT_InvoiceTo] UNIQUEIDENTIFIER NOT NULL, 
    [INE_COT_InvoiceFor] UNIQUEIDENTIFIER NOT NULL, 
    [INE_IsPaid] BIT NOT NULL DEFAULT 0, 
    [INE_IsDeleted] BIT NOT NULL DEFAULT 0, 
    CONSTRAINT FK_INVOICES_SCHOOL FOREIGN KEY ([INE_SCL_School]) REFERENCES [Schools](SCL_PK),
    CONSTRAINT FK_INVOICES_INVOICEFROM FOREIGN KEY ([INE_COT_InvoiceFrom]) REFERENCES [Contacts](COT_PK),
    CONSTRAINT FK_INVOICES_INVOICETO FOREIGN KEY ([INE_COT_InvoiceTo]) REFERENCES [Contacts](COT_PK),
    CONSTRAINT FK_INVOICES_INVOICEFOR FOREIGN KEY ([INE_COT_InvoiceFor]) REFERENCES [Contacts](COT_PK),
)
