CREATE TABLE [dbo].[Location]
(
	[LON_PK] UNIQUEIDENTIFIER NOT NULL PRIMARY KEY DEFAULT NEWID(), 
    [LON_Address] VARCHAR(50) NOT NULL DEFAULT '', 
    [LON_Suburb] VARCHAR(20) NOT NULL DEFAULT '', 
    [LON_Postcode] VARCHAR(10) NOT NULL DEFAULT '', 
    [LON_State] VARCHAR(10) NOT NULL DEFAULT '', 
    [LON_Country] VARCHAR(20) NOT NULL DEFAULT ''
)
GO
