CREATE TABLE [dbo].[Locations]
(
	[LocationPK] UNIQUEIDENTIFIER NOT NULL PRIMARY KEY DEFAULT NEWID(), 
    [Address] VARCHAR(50) NOT NULL DEFAULT '', 
    [Suburb] VARCHAR(20) NOT NULL DEFAULT '', 
    [Postcode] VARCHAR(10) NOT NULL DEFAULT '', 
    [State] VARCHAR(10) NOT NULL DEFAULT '', 
    [Country] VARCHAR(20) NOT NULL DEFAULT ''
)
GO
