CREATE TABLE [dbo].[Parents]
(
	[PAT_PK] UNIQUEIDENTIFIER NOT NULL PRIMARY KEY DEFAULT NEWID(), 
    [PAT_COT_Contact] UNIQUEIDENTIFIER NOT NULL,
    CONSTRAINT FK_PARENTS_CONTACT FOREIGN KEY ([PAT_COT_Contact]) REFERENCES [Contacts](COT_PK),
)
