CREATE TABLE [dbo].[Parents]
(
	[ParentPK] UNIQUEIDENTIFIER NOT NULL PRIMARY KEY DEFAULT NEWID(), 
    [ContactPK] UNIQUEIDENTIFIER NOT NULL,
    CONSTRAINT FK_PARENTS_CONTACT FOREIGN KEY (ContactPK) REFERENCES [Contacts](ContactPK),
)
