CREATE TABLE [dbo].[Parent]
(
	[PAT_PK] UNIQUEIDENTIFIER NOT NULL PRIMARY KEY DEFAULT NEWID(), 
    [PAT_COT_Contact] UNIQUEIDENTIFIER NOT NULL,
    CONSTRAINT FK_PARENT_CONTACT FOREIGN KEY ([PAT_COT_Contact]) REFERENCES [Contact](COT_PK),
)
