CREATE TABLE [dbo].[SchoolEnrolments]
(
	[SchoolEnrolmentPK] UNIQUEIDENTIFIER NOT NULL PRIMARY KEY DEFAULT NEWID(), 
    [ClassPK] UNIQUEIDENTIFIER NOT NULL, 
    [StudentPK] UNIQUEIDENTIFIER NOT NULL,
    CONSTRAINT FK_SCHOOLENROLMENTS_CLASS FOREIGN KEY ([ClassPK]) REFERENCES [Classes](ClassPK),
    CONSTRAINT FK_SCHOOLENROLMENTS_STUDENT FOREIGN KEY ([StudentPK]) REFERENCES [Students](StudentPK),
)
