CREATE TABLE [dbo].[SchoolEnrolments]
(
	[SE_PK] UNIQUEIDENTIFIER NOT NULL PRIMARY KEY DEFAULT NEWID(), 
    [SE_CLS_Class] UNIQUEIDENTIFIER NOT NULL, 
    [SE_STD_Student] UNIQUEIDENTIFIER NOT NULL,
    CONSTRAINT FK_SCHOOLENROLMENTS_CLASS FOREIGN KEY ([SE_CLS_Class]) REFERENCES [Classes](CLS_PK),
    CONSTRAINT FK_SCHOOLENROLMENTS_STUDENT FOREIGN KEY ([SE_STD_Student]) REFERENCES [Students](STD_PK),
)
