CREATE TABLE [dbo].[School]
(
	[SCL_PK] UNIQUEIDENTIFIER NOT NULL PRIMARY KEY DEFAULT NEWID(), 
    [SCL_Name] VARCHAR(50) NOT NULL DEFAULT '', 
    [SCL_LON_Location] UNIQUEIDENTIFIER NOT NULL,
    [SCL_USR_Principle] UNIQUEIDENTIFIER NOT NULL, 
    [SCL_USR_ContactUser] UNIQUEIDENTIFIER NULL, 
    CONSTRAINT FK_SCHOOL_LOCATION FOREIGN KEY ([SCL_LON_Location]) REFERENCES [Location](LON_PK),
    CONSTRAINT FK_SCHOOL_PRINCIPLE FOREIGN KEY (SCL_USR_Principle) REFERENCES [User](USR_PK),
    CONSTRAINT FK_SCHOOL_CONTACT_USER FOREIGN KEY ([SCL_USR_ContactUser]) REFERENCES [User](USR_PK),
)
