CREATE TABLE [dbo].[SchoolTerm]
(
	[ST_PK] UNIQUEIDENTIFIER NOT NULL PRIMARY KEY DEFAULT NEWID(), 
    [ST_Description] VARCHAR(20) NOT NULL DEFAULT '',
    [ST_StartDate] DATE NOT NULL, 
    [ST_EndDate] DATE NOT NULL, 
    [ST_SCL_School] UNIQUEIDENTIFIER NOT NULL,
    CONSTRAINT FK_SCHOOL_TERM_SCHOOL FOREIGN KEY ([ST_SCL_School]) REFERENCES [School](SCL_PK),
)
