CREATE TABLE [dbo].[Schools]
(
	[SCL_PK] UNIQUEIDENTIFIER NOT NULL PRIMARY KEY DEFAULT NEWID(), 
    [SCL_Name] VARCHAR(50) NOT NULL DEFAULT '', 
    [SCL_LON_Location] UNIQUEIDENTIFIER NOT NULL,
    [SCL_USR_Principle] UNIQUEIDENTIFIER NOT NULL, 
    [SCL_USR_ContactUser] UNIQUEIDENTIFIER NULL, 
    CONSTRAINT FK_SCHOOLS_LOCATION FOREIGN KEY ([SCL_LON_Location]) REFERENCES [Locations](LON_PK),
    CONSTRAINT FK_SCHOOLS_PRINCIPLE FOREIGN KEY (SCL_USR_Principle) REFERENCES [Users](USR_PK),
    CONSTRAINT FK_SCHOOLS_CONTACT_USER FOREIGN KEY ([SCL_USR_ContactUser]) REFERENCES [Users](USR_PK),
)
