CREATE TABLE [dbo].[SchoolTerms]
(
	[SchoolTermPK] UNIQUEIDENTIFIER NOT NULL PRIMARY KEY DEFAULT NEWID(), 
    [Description] VARCHAR(20) NOT NULL DEFAULT '',
    [StartDate] DATE NOT NULL, 
    [EndDate] DATE NOT NULL, 
    [SchoolPK] UNIQUEIDENTIFIER NOT NULL,
    CONSTRAINT FK_SCHOOLTERMS_SCHOOL FOREIGN KEY ([SchoolPK]) REFERENCES [Schools](SchoolPK),
)
