CREATE TABLE [dbo].[Schools]
(
	[SchoolPK] UNIQUEIDENTIFIER NOT NULL PRIMARY KEY DEFAULT NEWID(), 
    [Name] VARCHAR(50) NOT NULL DEFAULT '', 
    [LocationPK] UNIQUEIDENTIFIER NOT NULL,
    [PrincipleUserPK] UNIQUEIDENTIFIER NOT NULL, 
    [ContactUserPK] UNIQUEIDENTIFIER NULL,
    CONSTRAINT FK_SCHOOLS_LOCATION FOREIGN KEY ([LocationPK]) REFERENCES [Locations](LocationPK),
    CONSTRAINT FK_SCHOOLS_PRINCIPLE FOREIGN KEY (PrincipleUserPK) REFERENCES [Users](UserPK),
    CONSTRAINT FK_SCHOOLS_CONTACT_USER FOREIGN KEY (ContactUserPK) REFERENCES [Users](UserPK),
)
