CREATE TABLE [dbo].[SchoolVariable]
(
	[SV_PK] UNIQUEIDENTIFIER NOT NULL PRIMARY KEY DEFAULT NEWID(), 
    [SV_SCL_School] UNIQUEIDENTIFIER NOT NULL, 
    [SV_Name] VARCHAR(30) NOT NULL DEFAULT '', 
    [SV_Value] VARCHAR(30) NOT NULL DEFAULT '',
    CONSTRAINT FK_SCHOOLVARIABLE_SCHOOL FOREIGN KEY ([SV_SCL_School]) REFERENCES [School](SCL_PK),
)
