CREATE TABLE [dbo].[SchoolVariables]
(
	[SV_PK] UNIQUEIDENTIFIER NOT NULL PRIMARY KEY DEFAULT NEWID(), 
    [SV_SCL_School] UNIQUEIDENTIFIER NOT NULL, 
    [SV_Name] VARCHAR(30) NOT NULL DEFAULT '', 
    [SV_Value] VARCHAR(30) NOT NULL DEFAULT '',
    CONSTRAINT FK_SCHOOLVARIABLES_SCHOOL FOREIGN KEY ([SV_SCL_School]) REFERENCES [Schools](SCL_PK),
)
