CREATE TABLE [dbo].[SchoolVariables]
(
	[SchoolVariablePK] UNIQUEIDENTIFIER NOT NULL PRIMARY KEY DEFAULT NEWID(), 
    [SchoolPK] UNIQUEIDENTIFIER NOT NULL, 
    [Name] VARCHAR(30) NOT NULL DEFAULT '', 
    [Value] VARCHAR(30) NOT NULL DEFAULT '',
    CONSTRAINT FK_SCHOOLVARIABLES_SCHOOL FOREIGN KEY ([SchoolPK]) REFERENCES [Schools](SchoolPK),
)
