CREATE TABLE [dbo].[SchoolOpenClasses]
(
	[SchoolOpenClassPK] UNIQUEIDENTIFIER NOT NULL PRIMARY KEY DEFAULT NEWID(), 
    [SchoolPK] UNIQUEIDENTIFIER NOT NULL, 
    [SchoolTermPK] UNIQUEIDENTIFIER NULL, 
    [ClassPK] UNIQUEIDENTIFIER NOT NULL,
    CONSTRAINT FK_SCHOOLOPENCLASSES_SCHOOL FOREIGN KEY ([SchoolPK]) REFERENCES [Schools](SchoolPK),
    CONSTRAINT FK_SCHOOLOPENCLASSES_SCHOOLTERM FOREIGN KEY ([SchoolTermPK]) REFERENCES [SchoolTerms](SchoolTermPK),
    CONSTRAINT FK_SCHOOLOPENCLASSES_CLASS FOREIGN KEY ([ClassPK]) REFERENCES [Classes](ClassPK)

)
