CREATE TABLE [dbo].[Students]
(
	[STD_PK] UNIQUEIDENTIFIER NOT NULL PRIMARY KEY DEFAULT NEWID(), 
    [STD_COT_Contact] UNIQUEIDENTIFIER NOT NULL,
    [STD_PAT_Parent1] UNIQUEIDENTIFIER NULL, 
    [STD_PAT_Parent2] UNIQUEIDENTIFIER NULL, 
    [STD_PaidToDate] DATE NULL, 
    CONSTRAINT FK_STUDENTS_CONTACT FOREIGN KEY ([STD_COT_Contact]) REFERENCES [Contacts](COT_PK),
)
