CREATE TABLE [dbo].[Students]
(
	[StudentPK] UNIQUEIDENTIFIER NOT NULL PRIMARY KEY DEFAULT NEWID(), 
    [ContactPK] UNIQUEIDENTIFIER NOT NULL,
    [Parent1PK] UNIQUEIDENTIFIER NULL, 
    [Parent2PK] UNIQUEIDENTIFIER NULL,
    [PaidToDate] DATE NULL,
    [IsActive] BIT NOT NULL DEFAULT (1),
    [IsDeleted] BIT NOT NULL DEFAULT (0),
    CONSTRAINT FK_STUDENTS_CONTACT FOREIGN KEY (ContactPK) REFERENCES [Contacts](ContactPK),
    CONSTRAINT FK_STUDENTS_PARENT1 FOREIGN KEY (Parent1PK) REFERENCES [Parents](ParentPK),
    CONSTRAINT FK_STUDENTS_PARENT2 FOREIGN KEY (Parent2PK) REFERENCES [Parents](ParentPK),
)
