CREATE TABLE [dbo].[Teacher]
(
	[TER_PK] UNIQUEIDENTIFIER PRIMARY KEY default NEWID(),
    [TER_COT_Contact] UNIQUEIDENTIFIER NOT NULL,
	CONSTRAINT FK_TEACHER_CONTACT FOREIGN KEY ([TER_COT_Contact]) REFERENCES [Contact](COT_PK),
)
