CREATE TABLE [dbo].[Teachers]
(
	[TeacherPK] UNIQUEIDENTIFIER PRIMARY KEY default NEWID(),
	[AvailableDays] VARCHAR(7) NOT NULL DEFAULT '-------',
	[Salary] MONEY NULL,
    [ContactPK] UNIQUEIDENTIFIER NOT NULL,
	CONSTRAINT FK_TEACHERS_CONTACT FOREIGN KEY ([ContactPK]) REFERENCES [Contacts](ContactPK),
)
