CREATE TABLE [dbo].[Teachers]
(
	[TER_PK] UNIQUEIDENTIFIER PRIMARY KEY default NEWID(),
    [TER_COT_Contact] UNIQUEIDENTIFIER NOT NULL,
	CONSTRAINT FK_TEACHERS_CONTACT FOREIGN KEY ([TER_COT_Contact]) REFERENCES [Contacts](COT_PK),
)
