CREATE TABLE [dbo].[Transaction]
(
	[TRN_PK] UNIQUEIDENTIFIER NOT NULL PRIMARY KEY DEFAULT NEWID(), 
    [TRN_TransactionDate] DATE NOT NULL, 
    [TRN_SCL_School] UNIQUEIDENTIFIER NOT NULL, 
    [TRN_Description] NVARCHAR(100) NOT NULL DEFAULT '', 
    [TRN_IsCredit] BIT NOT NULL DEFAULT 0, 
    [TRN_Amount] MONEY NOT NULL DEFAULT 0, 
    [TRN_COT_Payer] UNIQUEIDENTIFIER NOT NULL, 
    [TRN_COT_Payee] UNIQUEIDENTIFIER NOT NULL,
    CONSTRAINT FK_TRANSACTION_SCHOOL FOREIGN KEY ([TRN_SCL_School]) REFERENCES [School](SCL_PK),
    CONSTRAINT FK_TRANSACTION_PAYER FOREIGN KEY ([TRN_COT_Payer]) REFERENCES [Contact](COT_PK),
    CONSTRAINT FK_TRANSACTION_PAYEE FOREIGN KEY ([TRN_COT_Payee]) REFERENCES [Contact](COT_PK),
)
