CREATE TABLE [dbo].[Transactions]
(
	[TRN_PK] UNIQUEIDENTIFIER NOT NULL PRIMARY KEY DEFAULT NEWID(), 
    [TRN_TransactionDate] DATE NOT NULL, 
    [TRN_SCL_School] UNIQUEIDENTIFIER NOT NULL, 
    [TRN_Description] NVARCHAR(100) NOT NULL DEFAULT '', 
    [TRN_IsCredit] BIT NOT NULL DEFAULT 0, 
    [TRN_Amount] MONEY NOT NULL DEFAULT 0, 
    [TRN_COT_Payer] UNIQUEIDENTIFIER NOT NULL, 
    [TRN_COT_Payee] UNIQUEIDENTIFIER NOT NULL,
    CONSTRAINT FK_TRANSACTIONS_SCHOOL FOREIGN KEY ([TRN_SCL_School]) REFERENCES [Schools](SCL_PK),
    CONSTRAINT FK_TRANSACTIONS_PAYER FOREIGN KEY ([TRN_COT_Payer]) REFERENCES [Contacts](COT_PK),
    CONSTRAINT FK_TRANSACTIONS_PAYEE FOREIGN KEY ([TRN_COT_Payee]) REFERENCES [Contacts](COT_PK),
)
