CREATE TABLE [dbo].[User]
(
	[USR_PK] UNIQUEIDENTIFIER NOT NULL PRIMARY KEY DEFAULT NEWID(), 
    [USR_LoginName] VARCHAR(50) NOT NULL DEFAULT '', 
    [USR_Password] VARCHAR(20) NOT NULL DEFAULT '', 
    [USR_UR_Role] UNIQUEIDENTIFIER NOT NULL,
    [USR_RegistrationStartDate] DATE NULL, 
    [USR_LicenseExpireDate] DATE NULL, 
    [USR_CreatedDate] DATE NULL, 
    CONSTRAINT FK_USER_USERROLE FOREIGN KEY ([USR_UR_Role]) REFERENCES [UserRole](UR_PK),
)
