CREATE TABLE [dbo].[Users]
(
	[UserPK] UNIQUEIDENTIFIER NOT NULL PRIMARY KEY DEFAULT NEWID(), 
    [LoginName] VARCHAR(50) NOT NULL DEFAULT '', 
    [Password] VARCHAR(20) NOT NULL DEFAULT '', 
    [UserRolePK] UNIQUEIDENTIFIER NOT NULL,
    [RegistrationStartDate] DATE NULL, 
    [LicenseExpiryDate] DATE NULL, 
    [CreatedDate] DATE NULL,
    CONSTRAINT FK_USERS_USERROLE FOREIGN KEY ([UserRolePK]) REFERENCES [UserRoles](UserRolePK),
)
