CREATE TABLE [dbo].[User]
(
	[USR_PK] UNIQUEIDENTIFIER NOT NULL PRIMARY KEY DEFAULT NEWID(), 
    [USR_FristName] NCHAR(20) NOT NULL DEFAULT '', 
    [USR_LastName] NCHAR(20) NOT NULL DEFAULT '', 
    [USR_LoginName] VARCHAR(50) NOT NULL DEFAULT '', 
    [USR_Email] VARCHAR(50) NOT NULL DEFAULT '', 
    [USR_PhoneNo] VARCHAR(50) NULL, 
    [USR_Address] VARCHAR(150) NULL, 
    [USR_Password] VARCHAR(20) NOT NULL DEFAULT '', 
    [USR_UR_Role] UNIQUEIDENTIFIER NOT NULL,
    [USR_RegistrationStartDate] DATE NULL, 
    [USR_LicenseExpireDate] DATE NULL, 
    [USR_CreatedDate] DATE NULL, 
    [USR_IsDeleted] BIT NOT NULL DEFAULT 0, 
    [USR_IsActive] BIT NOT NULL DEFAULT 1, 
    CONSTRAINT FK_USER_USERROLE FOREIGN KEY ([USR_UR_Role]) REFERENCES [UserRole](UR_PK),

)
